# Generated by Django 5.0.3 on 2024-03-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recepts", "0002_recept_category_alter_recept_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recept",
            name="time",
            field=models.CharField(max_length=10),
        ),
    ]
